server:
  servlet:
    context-path: /api
spring:
  application:
    name: assets-service
  datasource:
    url: jdbc:postgresql://localhost:9876/evidentor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  grpc:
    server:
      port: 9093
      reflection:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
debug: false